apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: helloworld
spec:
  containers:
  - name: nginx-arjun
    image: nginx
    ports:
    - containerPort: 80
  - name: kundru-k8s-demo
    image: arjunachari12/k8s-demo
    ports:
    - containerPort: 81
